version: '3.4'
services:
  ontop:
    image: ontop/ontop-endpoint:4.1.0
    container_name: bgee-ontop
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/bgee_v14_genex.owl
      ONTOP_MAPPING_FILE: /opt/ontop/input/bgee_v14_genex.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/bgee_v14_genex.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/bgee_v14_genex.toml
      ONTOP_CORS_ALLOWED_ORIGINS: '*'
      ONTOP_DEV_MODE: '${ONTOP_DEV_MODE}'
    ports:
      - '0.0.0.0:${ONTOP_PORT}:8080'
    volumes:
      - ./obda:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
    depends_on:
      - "pgsql"
    entrypoint: [ 
        "/opt/ontop/input/wait-for-it.sh", 
        "bgee-pgsql:5432", 
        "--timeout=0", 
        "--strict", 
        "--", 
        "/opt/ontop/entrypoint.sh" ]
  pgsql:
    image: postgres:13.2
    container_name: bgee-pgsql
    #restart: unless-stopped
    ports:
      - '0.0.0.0:${POSTGRES_PORT}:5432'
    volumes:
      - ./data/pgsql:/docker-entrypoint-initdb.d
      - data-pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
volumes:
  data-pgsql:
      name: bgee-data-pgsql
